### PR TITLE
Allow either the sender or the receiver to be the server

### PR DESCRIPTION
**Pull request by ArtskydJ**
Notable changes:
- Fix readme headers for npm
- Allow either the sender or the receiver to be the server
  - Split server and client pieces into separate files
  - Update docs to reflect changes (usage.txt, README.md)
- Update minimist
- Add tests

### CODE REVIEW

**Comment by ArtskydJ** [comment]
@gangleri Thanks for merging! 

P.S. Any chance of an npm release?

**Comment by gangleri** [comment]
What's your npm handle and I'll add you to publishers

**Comment by ArtskydJ** [comment]
It is [~artskydj](https://www.npmjs.com/~artskydj).

**Comment by gangleri** [comment]
@ArtskydJ you are an owner on npm now. Let me know if you have any problems.

Thanks for contributing to this

**Comment by ArtskydJ** [comment]
You're welcome! Thanks for accepting the PR. :)

**Pull request merged**
